apiVersion: v1
data:
  sync-registry.json: |-
    {
    	"tasks": [],
    	"methods": [
    		{
    			"type": "watch",
    			"enable": true
    		},
    		{
    			"type": "pull",
    			"enable": true,
    			"interval": "60s"
    		}
    	],
    	"health_check": {
    		"enable": true
    	},
    	"report": {
    		"interval" : "1m",
    		"targets": [
    			{
    				"type": "file",
    				"enable": true
    			}
    		]
    	}
    }
  sync-config.json: |-
    {
    	"tasks": [],
    	"methods": [
    		{
    			"type": "watch",
    			"enable": true
    		},
    		{
    			"type": "pull",
    			"enable": true,
    			"interval": "60s"
    		}
    	],
    	"health_check": {
    		"enable": true
    	},
    	"report": {
    		"interval" : "1m",
    		"targets": [
    			{
    				"type": "file",
    				"enable": true
    			}
    		]
    	}
    }
kind: ConfigMap
metadata:
  name: polaris-sync-config
  namespace: polaris-system